### ISSUE TITLE
Error parsing Chrome advisory - too many values to unpack

### ISSUE THREAD

**Issue by pedrohc** [mprpic/advisory-parser#25]
URL: https://chromereleases.googleblog.com/2020/08/stable-channel-update-for-desktop_25.html

```
... AdvisoryParser.parse_from_url(advisory_url)
  File "/usr/lib/python3.7/site-packages/advisory_parser/parser.py", line 24, in parse_from_url
    return parse_chrome_advisory(url)
  File "/usr/lib/python3.7/site-packages/advisory_parser/parsers/chrome.py", line 62, in parse_chrome_advisory
    metadata, text = line.split(':')
ValueError: too many values to unpack (expected 2)
```

**Comment by tausif-rh** [comment]
https://github.com/mprpic/advisory-parser/pull/26 helped parse this one.  However, review needed as this works for the recent advisories. Not an older one I found below, if it matters:

sfm2 flaw create -a https://chromereleases.googleblog.com/2019/03/stable-channel-update-for-desktop.html
