### ISSUE TITLE
Error parsing oracle advisory when retrieving cvss score

### ISSUE THREAD

**Issue by pedrohc** [mprpic/advisory-parser#8]
Description of problem:

While trying to parse Oracle October critical patch advisory: https://www.oracle.com/security-alerts/cpuoct2019verbose.html

```
Traceback (most recent call last):
...
  File "/usr/lib/python3.7/site-packages/advisory_parser/parser.py", line 35, in parse_from_url
    return parse_mysql_advisory(url)
  File "/usr/lib/python3.7/site-packages/advisory_parser/parsers/mysql.py", line 116, in parse_mysql_advisory
    description, cvss_text = re.split('\n *CVSS v3\.0', description)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by thoger** [comment]
A quick fix for this is to accept not only spaces, but also tabs (or any whitespaces) in between beginning of the line and CVSS v3.0 string.  Something like:

```python
description, cvss_text = re.split('\n\s*CVSS v3\.0', description)
```
A more future-proof approach may be to `.strip()` items added to the `description` list (`element.string` and `element.text`).
